
# tap repositories and their packages

## caskroom/cask
tap caskroom/cask
brew brew-cask
cask adobe-air
cask adobe-dng-converter
cask alfred
cask amazon-cloud-drive
cask android-file-transfer
cask appcleaner
cask atom
cask audio-hijack
cask bittorrent-sync
cask chefdk
cask coteditor
cask dayone-cli
cask dropbox
cask fission
cask flash-player
cask flickr-uploadr
cask flip4mac
cask github-desktop
cask gmvault
cask google-drive
cask google-japanese-ime
cask google-photos-backup
cask google-web-designer
cask handbrake
cask ibank
cask igetter
cask imagealpha
cask imageoptim
cask karabiner
cask libreoffice
cask lilypond
cask linein
cask miro-video-converter
cask mpeg-streamclip
cask musescore
cask omnigraffle
cask omnioutliner
cask omnipresence
cask opera
cask picasa
cask scrivener
cask send-to-kindle
cask sigil
cask silverlight
cask skype
cask transmission
cask transmit
cask virtualbox
cask vlc
cask xld
cask xquartz

## caskroom/versions
tap caskroom/versions
cask firefox-ja
cask sublime-text-dev

## homebrew/boneyard
tap homebrew/boneyard
brew git-flow-clone

## rcmdnk/file
tap rcmdnk/file
brew brew-file

# Other Homebrew packages
brew autoconf
brew automake
brew cairo
brew clisp
brew cloog
brew czmq
brew faac
brew ffmpeg
brew fontconfig
brew fontforge
brew freetype
brew gauche
brew gcc
brew gdbm
brew gettext
brew ghc
brew git
brew git-flow
brew glib
brew gmp
brew gobject-introspection
brew harfbuzz
brew hg-flow
brew icu4c
brew isl
brew jbig2dec
brew jpeg
brew lame
brew libdvdcss
brew libffi
brew libmpc
brew libpng
brew libsigsegv
brew libtiff
brew libtool
brew libunistring
brew libvo-aacenc
brew libxml2
brew libyaml
brew little-cms2
brew lv
brew mcrypt
brew mercurial
brew mftrace
brew mhash
brew mpfr
brew nkf
brew node
brew openssl
brew p7zip
brew pango
brew pixman
brew pkg-config
brew potrace
brew python
brew rbenv
brew rbenv-bundler
brew readline
brew ruby-build
brew smlnj
brew spawn-fcgi
brew sqlite
brew t1utils
brew texi2html
brew texinfo
brew vim
brew wget
brew x264
brew xvid
brew xz
brew yasm
brew youtube-dl
brew zeromq

# App Store applications
appstore 1Password
appstore Aperture
appstore CloudApp
appstore Coda 2
appstore Day One
appstore Evernote
appstore GarageBand
appstore Growl
appstore Hype
appstore iBooks Author
appstore iMovie
appstore iPhoto
appstore Keynote
appstore Kindle
appstore LINE
appstore MARKETSPEED
appstore MindNode Pro
appstore MultiMarkdown Composer
appstore Numbers
appstore OmniFocus
appstore OneDrive
appstore Pages
appstore Pixelmator
appstore Pocket
appstore Skitch
appstore SoundCloud
appstore StuffIt Expander
appstore Twitter
appstore Xcode
