
# tap repositories and their packages

tap argon/mas
brew mas

tap caskroom/cask
brew brew-cask
cask adobe-air
cask adobe-dng-converter
cask alfred
cask amazon-cloud-drive
cask android-file-transfer
cask appcleaner
cask atom
cask audio-hijack
cask banktivity
cask bittorrent-sync
cask chefdk
cask coteditor
cask dayone-cli
cask dropbox
cask fission
cask flash-player
cask flickr-uploadr
cask flip4mac
cask flux
cask github-desktop
cask gmvault
cask google-chrome
cask google-drive
cask google-hangouts
cask google-japanese-ime
cask google-photos-backup
cask google-web-designer
cask handbrake
cask haskell-platform
cask igetter
cask imagealpha
cask imageoptim
cask karabiner
cask libreoffice
cask lilypond
cask linein
cask miro-video-converter
cask mpeg-streamclip
cask musescore
cask omnigraffle
cask omnioutliner
cask omnipresence
cask opera
cask scrivener
cask send-to-kindle
cask sigil
cask skype
cask transmission
cask transmit
cask vagrant
cask virtualbox
cask vlc
cask wordpresscom
cask xld
cask xquartz

tap caskroom/fonts
cask font-source-han-code-jp

tap caskroom/versions
cask firefox-ja
cask sublime-text-dev

tap homebrew/boneyard
brew git-flow-clone

tap rcmdnk/file
brew brew-file

# Other Homebrew packages
brew aspcud
brew autoconf
brew automake
brew cairo
brew camlp5
brew clasp
brew clisp
brew cloog
brew czmq
brew elixir
brew erlang
brew faac
brew ffmpeg
brew fontconfig
brew fontforge
brew freetype
brew gauche
brew gcc
brew gdbm
brew gettext
brew git
brew git-flow
brew glib
brew gmp
brew gobject-introspection
brew gringo
brew harfbuzz
brew hg-flow
brew icu4c
brew isl
brew jbig2dec
brew jpeg
brew lame
brew leiningen
brew libdvdcss
brew libffi
brew libmpc
brew libpng
brew libsigsegv
brew libsodium
brew libtiff
brew libtool
brew libunistring
brew libvo-aacenc
brew libxml2
brew libyaml
brew little-cms2
brew lv
brew mcrypt
brew mercurial
brew mftrace
brew mhash
brew mpfr
brew nkf
brew node
brew ocaml
brew opam
brew openssl
brew p7zip
brew pango
brew pixman
brew pkg-config
brew potrace
brew pyenv
brew pyenv-virtualenv
brew pyenv-virtualenvwrapper
brew python
brew rbenv
brew rbenv-bundler
brew readline
brew ruby-build
brew smlnj
brew spawn-fcgi
brew sqlite
brew t1utils
brew texi2html
brew texinfo
brew unixodbc
brew vim
brew wget
brew wxmac
brew x264
brew xvid
brew xz
brew yasm
brew youtube-dl
brew zeromq
